### PR TITLE
Fixing small issues around the site

### PR DESCRIPTION
**Pull request by Frijol**

### CODE REVIEW

**Comment by johnnyman727** [comment]
@Frijol it looks like this doesn't quite solve the problem for #53.

I still get the old command line calls typed across my screen. I think you only changed the default text. You also need to change the contents of [this JavaScript file](https://github.com/tessel/tessel.io/blob/3f416638edeaa588a530ee231f6d6162812997b4/public/scripts/browserify/auto-typing.js#L61) that creates the animation.

**Comment by johnnyman727** [comment]
I went ahead and made the changes. I had to run `npm run build` to actually update the minified JS file that gets sent to the client. 

@Frijol if it works for you, feel free to merge.

**Comment by Frijol** [comment]
it did work for me, but also only after I did `npm run build`. @reconbot will we need to do anything special to make this propagate on deployment, or will `npm run build` be run there as well?

**Pull request merged**
