### PR TITLE
removes manufacturing language from homepage per SC meeting to-do

### PR DESCRIPTION
**Pull request by Frijol**
r? @tcr @johnnyman727 @rwaldron

### CODE REVIEW

**Comment by bennycode** [comment]
I like the "Build your idea faster" teaser. :sunny: Makes it attractive to hobbyists like me. :grin:

**Comment by Frijol** [comment]
Thanks for the suggestions!

The context on this PR (which I should have added originally): we get occasional inbound requests from people asking what their next steps are to scale their product up to manufacturing. When we built this page (back when we were a company), we had planned to support this - originally on a per-case basis, then eventually (and partly based on that expected experience) with our dreamed-of [Fractal](https://tessel.io/blog/101109458547/what-comes-next-fractal) product.

We may still work along these lines, but at the moment cannot support the per-case manufacturing help we had hoped to provide. At least - not as an entity. Individual team members may be up for contracting/consulting work. So this PR is intended to adjust the expectations of people visiting the tessel.io site.

It's a fine line. We have a lot of hobbyist and educational customers at the moment. We like and support them, but billing ourselves as "hobbyist" can be a red flag for people who are serious about creating products. We would like to support product developers as well, and in fact design decisions in Tessel 2's hardware layout still support an "optimize for manufacturing" use case.

I'm personally wary of the term "IoT", but maybe it's less buzzwordy than it used to be. Based on your suggestions, taking another pass :)

**Comment by Frijol** [comment]
What do you think @bennyn @reconbot?

**Comment by Frijol** [comment]
goin' for it while I have the wifi. Thanks!

**Comment by bennycode** [comment]
:+1:

**Pull request merged**
