### PR TITLE
Removes Python from homepage

### PR DESCRIPTION
**Pull request by Frijol**
Did I miss anything? review please @johnnyman727 

for deployment following https://github.com/tessel/this-week-in-tessel/pull/23

### CODE REVIEW

**Comment by johnnyman727** [comment]
I looked over the website and it looked good but as @reconbot said, we should just remove the Python code snippets (which can be easily found by searching for `js-py`).

**Comment by Frijol** [comment]
whoops, sorry, sloppy :/

**Comment by Frijol** [comment]
better?

**Comment by johnnyman727** [comment]
+1

**Pull request merged**
