### PR TITLE
Kb unbloat

### PR DESCRIPTION
**Pull request by Frijol**
Fixing https://github.com/tessel/tessel.io/issues/73 in a somewhat heavy-handed way, please feel free to nitpick choices.

Most likely to be controversial change:
I removed "shop" from the top nav bar.

Least likely to be controversial change:
took this old page
screen shot 2016-05-17 at 12 46 58 pm

and turned it into this new page
screen shot 2016-05-17 at 12 47 06 pm
screen shot 2016-05-17 at 12 47 39 pm

### CODE REVIEW

**Comment by Frijol** [comment]
any opinions on this @rwaldron @tcr @johnnyman727 @wyze @HipsterBrown @flaki

**Comment by flaki** [comment]
It sure looks much more welcoming @Frijol!

As for the "Shop" button, I'm fine with removing that - we may lose _some_ conversions in the process, but streamlines the site, and also doesn't fuel the confusion around whether Tessel is still a company/entity or not.

**Comment by HipsterBrown** [comment]
This is an absolutely rad and super helpful update. I love the more obvious links to various ways to communicate with others in the community and where to find a meetup about Tessel/hardware. 👍

**Comment by Frijol** [comment]
Cool, overwhelmingly positive response :) thanks guys.

Merging so it's all pretty for my talk tomorrow; continued conversation is welcome.

**Pull request merged**
