### PR TITLE
Small copy change

### PR DESCRIPTION
**Pull request by bennycode**

### CODE REVIEW

**Comment by wyze** [comment]
Thanks for contributing. Do you mind signing [this CLA](http://www.dojofoundation.org/about/claForm)?

**Comment by bennycode** [comment]
> Your Contributor License Agreement has been received and you are now eligible to contribute to all Dojo Foundation projects. Thank you for your contribution!

:smiley:

**Comment by wyze** [comment]
Thanks!

**Comment by Frijol** [comment]
Thanks for this!

**Pull request merged**
