### PR TITLE
change ship date to January

### PR DESCRIPTION
**Pull request by Frijol**
@johnnyman727 per https://github.com/tessel/this-week-in-tessel/pull/13/files#diff-0f85eec8f406e34a928f190eaa171fcd

Anywhere else I need to get? Already got Celery.

### CODE REVIEW

**Comment by johnnyman727** [comment]
Yes, the FAQs mention the ship date.

Do you think we should update the website after we send out the TWIT?

**Comment by Frijol** [comment]
I'd rather have it accurate sooner than wait on the TWIT.

**Comment by Frijol** [comment]
good catch on the FAQs, btw

**Comment by johnnyman727** [comment]
Sounds good. In that case :+1:

**Pull request merged**
